"$schema" = 'https://starship.rs/config-schema.json'
palette = "catppuccin_frappe"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$time\
$line_break$character"""

# Color palette (catppuccin)
[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[username]
show_always = true
style_user = "fg:sapphire"
format = '[$user]($style)'

[hostname]
ssh_only = false
format = '@[$hostname](blue)'
trim_at = '.companyname.com'
disabled = false

[directory]
style = "fg:peach"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "../"

[git_branch]
symbol = ""
style = "fg:maroon"
format = '[[ $symbol $branch](fg:maroon)]($style)'

[git_status]
style = "fg:maroon"
format = '[[($all_status$ahead_behind)](fg:maroon)]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:surface2"
format = '[[  $time](fg:surface2)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[󰣇 ❯](green)"
error_symbol = "[󰣇 ❯](red)"
vimcmd_symbol = "[󰣇 ❯](subtext0)"


